import fs from "fs";
import path from "path";

const localesDir = path.join(process.cwd(), "src/i18n/locales");

// Dedicated authentic dictionaries for all remaining non-English bundles
const DICTS: Record<string, Record<string, string>> = {
  ur: {
    "submit": "جمع کریں",
    "cancel": "منسوخ کریں",
    "loading": "لوڈ ہو رہا ہے...",
    "save": "محفوظ کریں",
    "search": "تلاش کریں",
    "close": "بند کریں",
    "statusVerified": "تصدیق شدہ",
    "statusSuggested": "تجویز کردہ",
    "statusCitizenConfirmed": "شہری کی تصدیق شدہ",
    "statusVerificationRequired": "تصدیق درکار ہے",
    "streetLayer": "اسٹریٹ میپ",
    "satelliteLayer": "سیٹلائٹ تصاویر",
    "adminDetailsToggle": "انتظامی درجہ بندی کی تفصیلات",
    "pageTitle": "اپنا مسئلہ بیان کریں",
    "pageSubtitle": "ہمیں بتائیں کہ کیا ہوا۔ انفورائٹ مصدقہ ذرائع کی بنیاد پر متعلقہ قانونی راستہ تجویز کرے گا۔",
    "pinCodeLabel": "پن کوڈ",
    "useCurrentLocation": "میرا موجودہ مقام استعمال کریں",
    "btnStartVoice": "अपनी زبان میں بولیں",
    "btnStopRecording": "روکیں"
  },
  bn: {
    "submit": "জমা দিন",
    "cancel": "বাতিল করুন",
    "loading": "লোড হচ্ছে...",
    "save": "সংরক্ষণ করুন",
    "search": "অনুসন্ধান করুন",
    "close": "বন্ধ করুন",
    "statusVerified": "যাচাইকৃত",
    "statusSuggested": "প্রস্তাবিত",
    "statusCitizenConfirmed": "নাগরিক দ্বারা নিশ্চিত",
    "statusVerificationRequired": "যাচাইকরণ প্রয়োজন",
    "streetLayer": "রাস্তার মানচিত্র",
    "satelliteLayer": "স্যাটেলাইট চিত্র",
    "adminDetailsToggle": "প্রশাসনিক কাঠামোর বিবরণ",
    "pageTitle": "আপনার সমস্যা বর্ণনা করুন",
    "pageSubtitle": "কী ঘটেছে তা জানান। ইনফোরাইট যাচাইকৃত তথ্যের ভিত্তিতে আইনি পথ নির্দেশ করবে।",
    "pinCodeLabel": "পিন কোড",
    "useCurrentLocation": "আমার বর্তমান অবস্থান ব্যবহার করুন",
    "btnStartVoice": "আপনার ভাষায় বলুন",
    "btnStopRecording": "থামান"
  },
  gu: {
    "submit": "સબમિટ કરો",
    "cancel": "રદ કરો",
    "loading": "લોડ થઈ રહ્યું છે...",
    "save": "સાચવો",
    "search": "શોધો",
    "close": "બંધ કરો",
    "statusVerified": "ચકાસાયેલ",
    "statusSuggested": "સૂચવેલ",
    "statusCitizenConfirmed": "નાગરિક દ્વારા પુષ્ટિ થયેલ",
    "statusVerificationRequired": "ચકાસણી જરૂરી",
    "streetLayer": "શેરી નકશો",
    "satelliteLayer": "સેટેલાઇટ છબી",
    "adminDetailsToggle": "વહીવટી માળખાની વિગતો",
    "pageTitle": "તમારી સમસ્યાનું વર્ણન કરો",
    "pageSubtitle": "શું બન્યું તે જણાવો। ઇન્ફોરાઇટ સત્તાવાર સ્ત્રોતોના આધારે કાનૂની માર્ગ બતાવશે।",
    "pinCodeLabel": "પિન કોડ",
    "useCurrentLocation": "મારું વર્તમાન સ્થાન વાપરો",
    "btnStartVoice": "તમારી ભાષામાં બોલો",
    "btnStopRecording": "અટકાવો"
  },
  ml: {
    "submit": "സമർപ്പിക്കുക",
    "cancel": "റദ്ദാക്കുക",
    "loading": "ലോഡ് ചെയ്യുന്നു...",
    "save": "സൂക്ഷിക്കുക",
    "search": "തിരയുക",
    "close": "അടയ്ക്കുക",
    "statusVerified": "സ്ഥിരീകരിച്ചു",
    "statusSuggested": "നിർദ്ദേശിച്ചത്",
    "statusCitizenConfirmed": "പൗരൻ സ്ഥിരീകരിച്ചത്",
    "statusVerificationRequired": "പരിശോധന ആവശ്യമാണ്",
    "streetLayer": "സ്ട്രീറ്റ് മാപ്പ്",
    "satelliteLayer": "ഉപഗ്രഹ ചിത്രങ്ങൾ",
    "adminDetailsToggle": "ഭരണപരമായ ശ്രേണി വിവരങ്ങൾ",
    "pageTitle": "നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക",
    "pageSubtitle": "എന്താണ് സംഭവിച്ചതെന്ന് വ്യക്തമാക്കുക। ഇൻഫോറൈറ്റ് ശരിയായ നിയമപരമായ വഴി കണ്ടെത്തും।",
    "pinCodeLabel": "പിൻ കോഡ്",
    "useCurrentLocation": "എന്റെ ലൊക്കേഷൻ ഉപയോഗിക്കുക",
    "btnStartVoice": "നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കുക",
    "btnStopRecording": "നിർത്തുക"
  },
  mr: {
    "submit": "प्रस्तुत करा",
    "cancel": "रद्द करा",
    "loading": "लोड होत आहे...",
    "save": "जतन करा",
    "search": "शोधा",
    "close": "बंद करा",
    "statusVerified": "सत्यापित",
    "statusSuggested": "सुचवलेले",
    "statusCitizenConfirmed": "नागरिकाने पुष्टी केलेले",
    "statusVerificationRequired": "पडताळणी आवश्यक",
    "streetLayer": "रस्ता नकाशा",
    "satelliteLayer": "उपग्रह प्रतिमा",
    "adminDetailsToggle": "प्रशासकीय रचना तपशील",
    "pageTitle": "तुमची समस्या सांगा",
    "pageSubtitle": "काय घडले ते सांगा। इन्फोराइट अधिकृत माहितीवर आधारित योग्य कायदेशीर मार्ग दाखवेल।",
    "pinCodeLabel": "पिन कोड",
    "useCurrentLocation": "माझे सध्याचे स्थान वापरा",
    "btnStartVoice": "तुमच्या भाषेत बोला",
    "btnStopRecording": "थांबवा"
  },
  od: {
    "submit": "ଦାଖଲ କରନ୍ତୁ",
    "cancel": "ବାତିଲ କରନ୍ତୁ",
    "loading": "ଲୋଡ୍ ହେଉଛି...",
    "save": "ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "search": "ସନ୍ଧାନ କରନ୍ତୁ",
    "close": "ବନ୍ଦ କରନ୍ତୁ",
    "statusVerified": "ଯାଞ୍ଚ ହୋଇଛି",
    "statusSuggested": "ପ୍ରସ୍ତାବିତ",
    "statusCitizenConfirmed": "ନାଗରିକ ଦ୍ୱାରା ନିଶ୍ଚିତ",
    "statusVerificationRequired": "ଯାଞ୍ଚ ଆବଶ୍ୟକ",
    "streetLayer": "ରାସ୍ତା ମାନଚିତ୍ର",
    "satelliteLayer": "ସାଟେଲାଇଟ୍ ଚିତ୍ର",
    "adminDetailsToggle": "ପ୍ରଶାସନିକ ସ୍ତର ବିବରଣୀ",
    "pageTitle": "ଆପଣଙ୍କର ସମସ୍ୟା ବର୍ଣ୍ଣନା କରନ୍ତୁ",
    "pageSubtitle": "କଣ ଘଟିଲା ଆମକୁ ଜଣାନ୍ତୁ। ଇନଫୋରାଇଟ୍ ସଠିକ୍ ଆଇନଗତ ପଦକ୍ଷେପ ଚିହ୍ନଟ କରିବ।",
    "pinCodeLabel": "ପିନ୍ କୋଡ୍",
    "useCurrentLocation": "ମୋର ବର୍ତ୍ତମାନର ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ",
    "btnStartVoice": "ଆପଣଙ୍କ ଭାଷାରେ କୁହନ୍ତୁ",
    "btnStopRecording": "ବନ୍ଦ କରନ୍ତୁ"
  },
  pa: {
    "submit": "ਜਮ੍ਹਾਂ ਕਰੋ",
    "cancel": "ਰੱਦ ਕਰੋ",
    "loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    "save": "ਸੰਭਾਲੋ",
    "search": "ਖੋਜੋ",
    "close": "ਬੰਦ ਕਰੋ",
    "statusVerified": "ਪ੍ਰਮਾਣਿਤ",
    "statusSuggested": "ਸੁਝਾਇਆ ਗਿਆ",
    "statusCitizenConfirmed": "ਨਾਗਰਿਕ ਦੁਆਰਾ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ",
    "statusVerificationRequired": "ਪੁਸ਼ਟੀ ਲੋੜੀਂਦੀ ਹੈ",
    "streetLayer": "ਸੜਕ ਨਕਸ਼ਾ",
    "satelliteLayer": "ਸੈਟੇਲਾਈਟ ਤਸਵੀਰਾਂ",
    "adminDetailsToggle": "ਪ੍ਰਬੰਧਕੀ ਢਾਂਚੇ ਦੇ ਵੇਰਵੇ",
    "pageTitle": "ਆਪਣੀ ਸਮੱਸਿਆ ਬਾਰੇ ਦੱਸੋ",
    "pageSubtitle": "ਕੀ ਵਾਪਰਿਆ ਸਾਨੂੰ ਦੱਸੋ। ਇਨਫੋਰਾਈਟ ਪ੍ਰਮਾਣਿਤ ਸਰੋਤਾਂ ਦੇ ਆਧਾਰ ਤੇ ਕਾਨੂੰਨੀ ਰਾਹ ਦੱਸੇਗਾ।",
    "pinCodeLabel": "ਪਿੰਨ ਕੋਡ",
    "useCurrentLocation": "ਮੇਰੀ ਮੌਜੂਦਾ ਸਥਿਤੀ ਵਰਤੋ",
    "btnStartVoice": "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ",
    "btnStopRecording": "ਰੋਕੋ"
  },
  ne: {
    "submit": "पेश गर्नुहोस्",
    "cancel": "रद्द गर्नुहोस्",
    "loading": "लोड हुँदैछ...",
    "save": "बचत गर्नुहोस्",
    "search": "खोज्नुहोस्",
    "close": "बन्द गर्नुहोस्",
    "statusVerified": "प्रमाणित",
    "statusSuggested": "सुझाइएको",
    "statusCitizenConfirmed": "नागरिक द्वारा पुष्टि",
    "statusVerificationRequired": "प्रमाणीकरण आवश्यक",
    "streetLayer": "सडक नक्सा",
    "satelliteLayer": "उपग्रह तस्वीर",
    "adminDetailsToggle": "प्रशासनिक संरचना विवरण",
    "pageTitle": "आफ्नो समस्या वर्णन गर्नुहोस्",
    "pageSubtitle": "के भयो हामीलाई भन्नुहोस्। इन्फोराइटले आधिकारिक स्रोतहरूको आधारमा कानुनी बाटो देखाउनेछ।",
    "pinCodeLabel": "पिन कोड",
    "useCurrentLocation": "मेरो हालको स्थान प्रयोग गर्नुहोस्",
    "btnStartVoice": "आफ्नो भाषामा बोल्नुहोस्",
    "btnStopRecording": "रोक्नुहोस्"
  },
  sa: {
    "submit": "समर्पयतु",
    "cancel": "निरस्यतु",
    "loading": "लोड् भवति...",
    "save": "संरक्षतु",
    "search": "अन्विष्यतु",
    "close": "पिदधातु",
    "statusVerified": "प्रमाणितम्",
    "statusSuggested": "परामृष्टम्",
    "statusCitizenConfirmed": "नागरिक-पुष्टीकृतम्",
    "statusVerificationRequired": "प्रमाणीकरणम् आवश्यकम्",
    "streetLayer": "मार्ग-मानचित्रम्",
    "satelliteLayer": "उपग्रह-चित्राणि",
    "adminDetailsToggle": "प्रशासनिक-श्रेणी-विवरणम्",
    "pageTitle": "स्वसमस्यां वर्णयतु",
    "pageSubtitle": "किं वृत्तम् इति वदतु। इन्फोराइट् प्रामाणिक-स्रोतांसि अनुसृत्य विधिक-मार्गदर्शनं करिष्यति।",
    "pinCodeLabel": "पिन-सङ्केतः",
    "useCurrentLocation": "मम वर्तमान-स्थानं प्रयुज्यताम्",
    "btnStartVoice": "स्वभाषायां वदतु",
    "btnStopRecording": "स्थगयतु"
  },
  mai: {
    "submit": "जमा करू",
    "cancel": "रद्द करू",
    "loading": "लोड भ रहल अछि...",
    "save": "सहेजू",
    "search": "खोजू",
    "close": "बंद करू",
    "statusVerified": "प्रमाणित",
    "statusSuggested": "सुझाओल",
    "statusCitizenConfirmed": "नागरिक द्वारा पुष्ट",
    "statusVerificationRequired": "सत्यापन आवश्यक",
    "streetLayer": "सड़क मानचित्र",
    "satelliteLayer": "उपग्रह चित्र",
    "adminDetailsToggle": "प्रशासनिक संरचना विवरण",
    "pageTitle": "अपन समस्या बताउ",
    "pageSubtitle": "की भेल से कहू। इन्फोराइट आधिकारिक स्रोत सं विधिक मार्गदर्शन करत।",
    "pinCodeLabel": "पिन कोड",
    "useCurrentLocation": "हमर वर्तमान स्थान प्रयोग करू",
    "btnStartVoice": "अपन भाषा मे बाजू",
    "btnStopRecording": "रोकू"
  },
  doi: {
    "submit": "जमा करो",
    "cancel": "रद्द करो",
    "loading": "लोड होआ करदा ऐ...",
    "save": "सांभो",
    "search": "खोजो",
    "close": "बंद करो",
    "statusVerified": "प्रमाणित",
    "statusSuggested": "सुझाया गेदा",
    "statusCitizenConfirmed": "नागरिक आसेआ पुष्ट",
    "statusVerificationRequired": "पुष्टि लोड़दी ऐ",
    "streetLayer": "सड़क नक्शा",
    "satelliteLayer": "उपग्रह तस्वीरें",
    "adminDetailsToggle": "प्रशासकीय रचना विवरण",
    "pageTitle": "अपनी समस्या दस्सो",
    "pageSubtitle": "केह् होआ सानू दस्सो। इन्फोराइट कान्नूनी राह् दस्सग।",
    "pinCodeLabel": "पिन कोड",
    "useCurrentLocation": "मेरा मौजूदा स्थान बरतो",
    "btnStartVoice": "अपनी भाशा च बोलो",
    "btnStopRecording": "रोको"
  },
  brx: {
    "submit": "गथायनाय",
    "cancel": "बातिल खालाम",
    "loading": "लोड जाबाय थादों...",
    "save": "दोनथुम",
    "search": "नायगिर",
    "close": "बन्द खालाम",
    "statusVerified": "फोरमान जाबाय",
    "statusSuggested": "सुबुरुन होनाय",
    "statusCitizenConfirmed": "सुबुंनि निसित",
    "statusVerificationRequired": "नायबिजिरनाय नांगौ",
    "streetLayer": "लामा मानसावगारि",
    "satelliteLayer": "उपग्रह सावगारि",
    "adminDetailsToggle": "सामलायनाय रोखोम",
    "pageTitle": "नोंनि जेंनाखौ फोरमाय",
    "pageSubtitle": "मा जादों फोरमाय। इन्फोराइट कानुनारि राह देखायगोन।",
    "pinCodeLabel": "पिन कोड",
    "useCurrentLocation": "आंनि दायो थानाय जायगाखौ बाहाय",
    "btnStartVoice": "गावनि रावजों बुं",
    "btnStopRecording": "थादो"
  },
  sat: {
    "submit": "ᱮᱢ ᱢᱮ",
    "cancel": "ᱵᱟᱹᱛᱤᱞ ᱢᱮ",
    "loading": "ᱞᱟᱫᱮᱜ ᱠᱟᱱᱟ...",
    "save": "ᱥᱟᱺᱪᱟᱣ ᱢᱮ",
    "search": "ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ",
    "close": "ᱵᱚᱸᱫᱽ ᱢᱮ",
    "statusVerified": "ᱯᱩᱥᱴᱟᱹᱣ ᱮᱱᱟ",
    "statusSuggested": "ᱥᱚᱞᱦᱟ",
    "statusCitizenConfirmed": "ᱦᱚᱲ ᱴᱷᱟᱹᱣᱠᱟᱹ",
    "statusVerificationRequired": "ᱯᱩᱥᱴᱟᱹᱣ ᱞᱟᱹᱠᱛᱤ",
    "streetLayer": "ᱰᱟᱦᱟᱨ ᱢᱮᱯ",
    "satelliteLayer": "ᱥᱟᱴᱮᱞᱟᱭᱤᱴ ᱪᱤᱛᱟᱹᱨ",
    "adminDetailsToggle": "ᱥᱟᱥᱚᱱᱤᱭᱟᱹ ᱵᱤᱵᱚᱨᱚᱱ",
    "pageTitle": "ᱟᱢᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱞᱟᱹᱭ ᱢᱮ",
    "pageSubtitle": "ᱪᱮᱫ ᱦᱩᱭ ᱟᱠᱟᱱᱟ ᱞᱟᱹᱭ ᱢᱮ᱾ ᱤᱱᱯᱷᱳᱨᱟᱭᱤᱴ ᱟᱹᱭᱤᱱ ᱰᱟᱦᱟᱨᱮ ᱩᱫᱩᱜᱟ᱾",
    "pinCodeLabel": "ᱯᱤᱱ ᱠᱳᱰ",
    "useCurrentLocation": "ᱤᱧᱟᱜ ᱱᱤᱛᱚᱜ ᱴᱷᱟᱶ ᱵᱮᱵᱷᱟᱨ ᱢᱮ",
    "btnStartVoice": "ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱨᱚᱲ ᱢᱮ",
    "btnStopRecording": "ᱛᱷᱟᱢᱵᱷᱟᱣ ᱢᱮ"
  },
  kok: {
    "statusVerified": "प्रमाणीत",
    "statusSuggested": "सुचयिल्लें",
    "statusCitizenConfirmed": "नागरीक पुष्टी",
    "statusVerificationRequired": "तपासणी गरजेची",
    "streetLayer": "रस्तो नकासो",
    "satelliteLayer": "उपग्रह चित्र",
    "adminDetailsToggle": "प्रशासकीय रचना तपशील"
  }
};

for (const [lang, map] of Object.entries(DICTS)) {
  const filePath = path.join(localesDir, `${lang}.ts`);
  if (!fs.existsSync(filePath)) continue;

  let content = fs.readFileSync(filePath, "utf8");

  for (const [k, v] of Object.entries(map)) {
    const regex = new RegExp(`("${k}":\\s*")[^"]*(")`);
    if (regex.test(content)) {
      content = content.replace(regex, `$1${v}$2`);
    }
  }

  fs.writeFileSync(filePath, content, "utf8");
  console.log(`Updated localized core strings in ${lang}.ts`);
}
